---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assogw-site-ingress
  labels:
    app: assogw-site
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  rules:
    - host: assogw.tortato.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assogw-site-service
                port:
                  number: 80

    - host: assogw.tortato.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assogw-site-service
                port:
                  number: 80

  tls:
    - hosts:
        - assogw.tortato.com
        - assogw.tortato.com.br
      secretName: assogw-tls-secret
